#image: ubuntu:14.04
#name: randomaas
#services:
#  - postgres
#script:
#  - docker build -t randomaas http://gitlab.juancastro.org/juan/randomaas/raw/master/Dockerfile
#
image: ubuntu
env:
    -  GOPATH==/var/cache/drone
script:
    -  go build
    -  go test –v
    -  go install
services:
    -  redis
notify:
  email:
    recipients:
      - centurylinkcloud@gmail.com
