#image: ubuntu:14.04
#name: randomaas
#services:
#  - postgres
#script:
#  - docker build -t randomaas http://gitlab.juancastro.org/juan/randomaas/raw/master/Dockerfile
#
image: randomaas
env:
    -  GOPATH==/var/cache/drone
script:
    -  git pull
    -  python tests/maintest.py
services:
    -  redis
notify:
  email:
    recipients:
      - krazybean1@yahoo.com
