image: ubuntu:14.04
env:
  - GOPATH=/var/cache/drone
  - DEBUG=true
script:
  - sudo apt-get -y install git
  - wget http://gitlab.juancastro.org/juan/randomaas/raw/master/Dockerfile
  - docker build -rm -t Dockerfile Randomaas
#services:
#  - dockerfile/
notify:
  email:
    recipients:
      - krazybean1@yahoo.com
