image: ubuntu:14.04
name: randomaas-test
script:
  - docker build -rm -t randomaastest http://gitlab.juancastro.org/juan/randomaas/raw/master/Dockerfile

notify:
  email:
    recipients:
    - krazybean1@yahoo.com
