image: ubuntu:14.04
env:
  - DEBUG=true
script:
  - apt-get install -y python
  - apt-get install -y python-pip
  - apt-get install -y virtualenv
  - apt-get install -y python-virtualenv
  - apt-get install -y git
  - git clone http://gitlab.juancastro.org/juan/randomaas.git
  - cd randomaas/
  - pip install -r requirements.txt

services:
  - redis
notify:
  email:
    recipients:
      - brad@drone.io
      - burke@drone.io
